services:
  - type: web
    name: library-book-locator
    env: python
    buildCommand: bash build.sh
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: "10000"
      - key: RENDER
        value: "true"
    disk:
      name: data
      mountPath: /data
      sizeGB: 1